hello-world/hello-world.yaml

Add the yaml representation of the hello-world tekton bundle.
This information was fetched from the existing material:
* podman pull quay.io/hacbs-release/hello-world:0.3-alpine
* podman inspect quay.io/hacbs-release/hello-world:0.3-alpine

Add hello-world YAML

---

definitions/hello-release/hello-release.yaml

Add TKN demo bundle

---

definitions/hello-release/hello-release.yaml

Demo release bundle

---

definitions/hello-release/hello-release.yaml

Demo workflow

---

definitions/hello-release/hello-release.yaml

Bundle demo

---

.github/workflows/tekton_bundle_push.yaml
scripts/mock_kube_config.sh
scripts/tkn_push_bundles.sh

Move workflow inline scripts to separate files.

---

.github/workflows/lint.yaml
.yamllint

The "with:" parameters was not properly aligned.

Bugfix: Correct indentation error in workflow yaml.

---

definitions/cleanup-workspace/README.md
definitions/cleanup-workspace/cleanup-workspace.yaml

This commits add a task to cleanup a given directory that
is contained in the provided tekton workspace.

feat(HACBS-565): add cleanup-workspace task

---

definitions/hello-release/hello-release.yaml

test: modify existing bundle to trigger CI.

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
LICENSE
README.md

As part of this PR I'm updating the README.md and adding new LICENSE, CONTRIBUTE.md and CODE_OF_CONDUCTS.md files.

docs: update repository documents

---

definitions/m6-release-pipeline/m6-release-pipeline.yaml

- include disabling cosign experimental features

m6 release pipeline

---

.github/scripts/tkn_push_bundles.sh
.github/workflows/lint.yaml
.github/workflows/tekton_bundle_push.yaml

feat(hacbs-994): Change CI to use catalog dir

---

catalog/pipeline/release/0.1/samples/sample_release_PipelineRun.yaml
catalog/pipeline/release/0.2/samples/sample_release_PipelineRun.yaml
catalog/task/apply-mapping/0.1/samples/sample_apply-mapping_TaskRun.yaml
catalog/task/cleanup-workspace/0.1/samples/sample_cleanup-workspace_TaskRun.yaml
catalog/task/prepare-validation/0.1/samples/sample_prepare-validation_TaskRun.yaml
catalog/task/push-application-snapshot/0.1/samples/sample_push-application-snapshot_TaskRun.yaml
catalog/task/skopeo-copy/0.1/samples/sample_skopeo-copy_TaskRun.yaml

Based on the existing testing runs.

feat(hacbs-1078): Add Boilerplate Sample Runs

---

catalog/pipeline/release/0.3/README.md
catalog/pipeline/release/0.3/release.yaml
catalog/pipeline/release/0.3/samples/sample_release_PipelineRun.yaml
catalog/pipeline/release/0.3/tests/run.yaml

adds version 0.3 of the Release Pipeline

feat(hacbs_1157): adds new PipelineRun version

---

catalog/pipeline/fbc-release/0.2/README.md
catalog/pipeline/fbc-release/0.2/fbc-release.yaml
catalog/pipeline/fbc-release/0.2/samples/sample_release_PipelineRun.yaml
catalog/pipeline/fbc-release/0.2/tests/run.yaml

See reference:
- https://github.com/hacbs-release/release-bundles/pull/64
- https://github.com/hacbs-release/release-bundles/pull/65
- https://github.com/hacbs-release/release-bundles/pull/66
Signed-off-by: Scott Hebert <shebert@redhat.com>

fix(hacbs-1583): update defn of task verify-enterprise-contract in fbc release

---

catalog/pipeline/deploy-release/0.1/README.md
catalog/pipeline/deploy-release/0.1/deploy-release.yaml
catalog/pipeline/deploy-release/0.1/samples/sample_release_PipelineRun.yaml
catalog/pipeline/deploy-release/0.1/tests/run.yaml
catalog/pipeline/deploy-release/OWNERS

For the simple deploy release case, there is no component mapping that needs to be performed. Only a ec validate.

deploy release pipeline 0.1

---

catalog/task/create-pyxis-image/0.1/create-pyxis-image.yaml

fix(HACBS-1261): fix TODO in create-pyxis-image image line

---

catalog/task/push-sbom-to-pyxis/0.1/README.md
catalog/task/push-sbom-to-pyxis/0.1/push-sbom-to-pyxis.yaml
catalog/task/push-sbom-to-pyxis/0.1/sample/sample_push-sbom-to-pyxis_TaskRun.yaml
catalog/task/push-sbom-to-pyxis/0.1/tests/run.yaml
catalog/task/push-sbom-to-pyxis/OWNERS

This is the first step. For now this task will
just get the sbom json file from the image
using cosign download sbom.
More work will be done in future PRs/stories.
Signed-off-by: Martin Malina <mmalina@redhat.com>

feat(HACBS-1551): add new push-sbom-to-pyxis task

---

catalog/pipeline/fbc-release/0.3/README.md
catalog/pipeline/fbc-release/0.3/fbc-release.yaml
catalog/pipeline/fbc-release/0.3/samples/sample_release_PipelineRun.yaml
catalog/pipeline/fbc-release/0.3/tests/run.yaml
catalog/pipeline/release/0.8/README.md
catalog/pipeline/release/0.8/release.yaml
catalog/pipeline/release/0.8/samples/sample_release_PipelineRun.yaml
catalog/pipeline/release/0.8/tests/run.yaml

Pipeline `metadata.name` should be the same as the `folder` name

Standardize pipeline names

---

catalog/pipeline/fbc-release/0.4/README.md
catalog/pipeline/fbc-release/0.4/fbc-release.yaml
catalog/pipeline/fbc-release/0.4/samples/sample_release_PipelineRun.yaml
catalog/pipeline/fbc-release/0.4/tests/run.yaml
catalog/task/create-internal-request/0.1/create-internal-request.yaml

Adds new pipeline and required fixes in the tasks.
- adds snapshot as fragment
- adding new pipeline version

chore: adds new pipeline version and task fixes

---

catalog/pipeline/push-to-external-registry/0.1/README.md
catalog/pipeline/push-to-external-registry/0.1/push-to-external-registry.yaml
catalog/pipeline/push-to-external-registry/0.1/samples/sample_push-to-external-registry_PipelineRun.yaml
catalog/pipeline/push-to-external-registry/0.1/tests/run.yaml
catalog/pipeline/push-to-external-registry/OWNERS

feat(HACBS-1262): add pipeline to push image to external registry

---

catalog/pipeline/push-to-external-registry/0.1/push-to-external-registry.yaml

fix: create pyxis entry after push in push-to-external-registry

---

catalog/pipeline/push-to-external-registry/0.2/README.md
catalog/pipeline/push-to-external-registry/0.2/push-to-external-registry.yaml
catalog/pipeline/push-to-external-registry/0.2/samples/sample_push-to-external-registry_PipelineRun.yaml
catalog/pipeline/push-to-external-registry/0.2/tests/run.yaml
catalog/task/create-pyxis-image/0.2/README.md
catalog/task/create-pyxis-image/0.2/create-pyxis-image.yaml
catalog/task/create-pyxis-image/0.2/samples/sample_create-pyxis-image_TaskRun.yaml
catalog/task/create-pyxis-image/0.2/tests/run.yaml

Signed-off-by: Scott Hebert <shebert@redhat.com>

fix(HACBS-1262): correct incorrect snapshot param

---

catalog/pipeline/fbc-release/0.5/README.md
catalog/pipeline/fbc-release/0.5/fbc-release.yaml
catalog/pipeline/fbc-release/0.5/samples/sample_release_PipelineRun.yaml
catalog/pipeline/fbc-release/0.5/tests/run.yaml
catalog/task/create-internal-request/0.2/README.md
catalog/task/create-internal-request/0.2/create-internal-request.yaml
catalog/task/create-internal-request/0.2/samples/sample_create-internal-request_TaskRun.yaml
catalog/task/create-internal-request/0.2/tests/run.yaml

- updates `fbc-release` to 0.5
- updates `create-internal-request` to 0.2

chore: updates Pipeline and Task

---

catalog/pipeline/release/0.9/README.md
catalog/pipeline/release/0.9/release.yaml
catalog/pipeline/release/0.9/samples/sample_release_PipelineRun.yaml
catalog/pipeline/release/0.9/tests/run.yaml

Update tag for ec-verify task bundle. 
See https://redhat-internal.slack.com/archives/C02FANRBZQD/p1677719763097719 for discussion.

fix(HACBS-1917): update tag of ec-task-bundle task

---

catalog/pipeline/push-to-external-registry/0.6/README.md
catalog/pipeline/push-to-external-registry/0.6/push-to-external-registry.yaml
catalog/task/create-pyxis-image/0.3/README.md
catalog/task/create-pyxis-image/0.3/create-pyxis-image.yaml
catalog/task/push-sbom-to-pyxis/0.1/README.md
catalog/task/push-sbom-to-pyxis/0.1/push-sbom-to-pyxis.yaml
catalog/task/push-sbom-to-pyxis/0.1/sample/sample_push-sbom-to-pyxis_TaskRun.yaml
catalog/task/push-sbom-to-pyxis/0.1/tests/run.yaml

Adapt the task to support multiple images on the input.
Also, add a second step to run the upload_sbom script for each sbom file.

feat(HACBS-1552): update upload sbom task

---

catalog/task/collect-data/0.1/README.md
catalog/task/collect-data/0.1/collect-data.yaml
catalog/task/collect-data/0.1/tests/test-collect-data-with-extra-data.yaml

- collect-data no longer stores the extraData in tekton result. It is stored in a json file.

feat(HACBS-2471): Convert collect-data to store result in json

---

catalog/task/update-infra-deployments/0.1/README.md
catalog/task/update-infra-deployments/0.1/samples/update-infra-deployments_TaskRun.yaml
catalog/task/update-infra-deployments/0.1/tests/run.yaml
catalog/task/update-infra-deployments/0.1/update-infra-deployments.yaml
catalog/task/update-infra-deployments/OWNERS

- We are re-using the update-infra-deployments task from build-templates
- We have updated it to use extraData and snapshot json files as input.
- Tests to be added later

feat(HACBS-2471): add update-infra-deployments task

---

catalog/task/push-snapshot/0.10/README.md
catalog/task/push-snapshot/0.10/push-snapshot.yaml
catalog/task/push-snapshot/0.10/samples/sample_push-snapshot_TaskRun.yaml
catalog/task/push-snapshot/0.10/tests/run.yaml

- Create tag based on full git sha

fix(HACBS-2471): create tag based on full git sha

---

catalog/pipeline/push-to-external-registry/0.15/README.md
catalog/pipeline/push-to-external-registry/0.15/push-to-external-registry.yaml
catalog/pipeline/push-to-external-registry/0.15/samples/sample_push-to-external-registry_PipelineRun.yaml
catalog/pipeline/push-to-external-registry/0.15/tests/run.yaml

- update rhtap-service-push
- update push-to-external-registry

feat(HACBS-2471): use v0.10 of push-snapshot
