Dockerfile
Similiar to how appstudio has an appstudio-utils container image that
they use as the base for their tekton tasks, this commit adds a
release-utils image that we can use for our release service tekton tasks.
=> feat: add Dockerfile for release-utils

definitions/component-mapping/component-mapping.yaml
This commit adds a milestone 5 definition containing a pipeline with just
one task. The task will retrieve the mapping file passed in as a parameter,
convert it into a json, and save it as a task result to be used by later
tasks.
=> feat(HACBS-472): fetch mapping file

definitions/component-mapping/component-mapping.yaml
This commit adds a tekton task to the component-mapping
bundle that will apply the provided mapping to the passed
ApplicationSnapshot. Images that do not exist in the
mapping will be removed, and images that do exist in the
mapping will have a key specifying their destination
added.
=> feat(HACBS-467): add tekton task to filter snapshot

definitions/fake-ec-validation/README.md, definitions/fake-ec-validation/validate_enterprise_contract.yaml
This bundle can be used to fake an EC validation. It contains a validate-enterprise-contract task to which a shouldFail parameter can be passed. This parameter will simulate an error in the validation process.
Signed-off-by: David Moreno García <damoreno@redhat.com>
=> feat(HACBS-562): add fake-ec-validation bundle

.github/scripts/tkn_push_bundles.sh, .github/workflows/tekton_bundle_push.yaml
The workflow has a new error creating the repo prior to pushing bundles.
```
Creating new repo: quay.io/hacbs-release/fake-ec-validation
{"message": "CSRF token was invalid or missing."}
```
* The API token exists on Quay, and has the correct permissions
requred to create new image repos.
* curl cmdline to list repos using the Quay oath2 API token was proven
to work from my laptop, so it's known to be good.
* The associated GitHub secret for the API token was updated to ensure
it was the same one established at Quay.
* Workflows were re-run to test the aforementioned things.
This commit is to help determine if the problem is with passing GitHub secret
contexts to the scripting environment. Other secret contexts were passed
from the outer environment, so this change aligns the Quay …
=> bug: troubleshooting quay API calls using token.

Dockerfile
Skopeo will be needed by one of our Tekton tasks. That task should use the release-utils image, so we need to update the Dockerfile to add it.
Signed-off-by: David Moreno García <damoreno@redhat.com>
=> feat(HACBS-599): add skopeo

definitions/prepare-validation/README.md, definitions/prepare-validation/prepare-validation.yaml
This commit adds the prepare-validation task which will extract the first
component's pullSpec from an application snapshot. It is just for m5 and
should be reverted later on, once the Enterprise Contract task accepts a
full snapshot instead of just an IMAGE_REF.
=> feat(HACBS-609): create prepare-validation task

Dockerfile
Tekton tasks need to have a HOME variable set to anything else than `/` so credentials can be copied.
Signed-off-by: David Moreno García <damoreno@redhat.com>
=> fix(HACBS-615): set HOME variable

definitions/apply-mapping/README.md, definitions/apply-mapping/apply-mapping.yaml
This commit modifies the apply-mapping task to return a result named
mapped. The value of mapped is true if the snapshot had a mapping
applied and false otherwise.
=> feat: return mapped result in apply-mapping

definitions/prepare-validation/prepare-validation.yaml
Add the -j option to the jq command used in the prepare
validation task.
=> fix: add option to jq in prepare-validation

definitions/skopeo-copy/skopeo-copy.yaml
* According to docs int types are not valid.
* This change allows `tkn bunlde push` cli to properly parse the yaml.
https://tekton.dev/docs/pipelines/tasks/#specifying-parameters
jira: hacbs-678
=> bug: Use type string instead of int in Tekton task

definitions/apply-mapping/README.md, definitions/apply-mapping/apply-mapping.yaml, definitions/prepare-validation/README.md, definitions/prepare-validation/prepare-validation.yaml, definitions/push-application-snapshot/push-application-snapshot.yaml
We are moving from the proof of concept ApplicationSnapshot CRD to
the production one maintained by the GitOps team. This commit changes
field names to reflect the names used in the GitOps CRD.
=> feat(HACBS-665): switch to GitOps ApplicationSnapshot CRD

README.md
It seems that text between `< >` is not showed by Markdown. I'm removing that as part of this commit.
Signed-off-by: David Moreno García <damoreno@redhat.com>
=> fix(HACBS-667): fix syntax typo

definitions/m5-release-pipeline/m5-release-pipeline.yaml
For demo time crunch purposes, we copied the git-clone task into our own bundle
and used it in the milestone 5 release pipeline. We should use the shared one
from redhat-appstudio. This commit switches to it.
=> fix: use shared git-clone task

.github/scripts/tkn_push_bundles.sh, .github/workflows/tekton_bundle_push.yaml, README.md
Remarks:
* Add "changed-files" action to CI workflow
* Configure action to diff  "definitons/*/*.yaml" files
* Update shell script use changed-files as input.
* Added `on: path` [workflow filter pattern](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet) to ONLY run when bundle definitions are part of the push.
* Accordingly, removed redundant path checking REGEX from the script.
This should allow the repo to re-enable merge-commits.
Jira: hacbs-692
=> feat: Introduce changed-files GitHub action.

catalog/pipeline/release/0.1/tests/run.yaml, catalog/pipeline/release/0.2/tests/run.yaml, catalog/task/apply-mapping/0.1/tests/run.yaml, catalog/task/cleanup-workspace/0.1/tests/run.yaml, catalog/task/prepare-validation/0.1/tests/run.yaml, catalog/task/push-application-snapshot/0.1/tests/run.yaml, catalog/task/skopeo-copy/0.1/tests/run.yaml
* Each pipeline & task version was given a boilerplate run.yaml
* These could also potentially serve as the sample runs
* The idea is tests will become more elaborate later
=> chore(hacbs-1077): add boilerplate task & pipeline runs for test

.github/scripts/tkn_push_bundles.sh
* The image repo does not allow tag for multiple imgages.
* we decided to stop having git branch & sha1 tags.
* we will use catalog version tags, image digests, or both.
=> bug(hacbs-1135): stop applying extra tags on bundle push

catalog/pipeline/release/0.3/README.md, catalog/pipeline/release/0.3/release.yaml, catalog/pipeline/release/0.3/samples/sample_release_PipelineRun.yaml, catalog/pipeline/release/0.3/tests/run.yaml
Changes `enterprisecontractpolicy` pipeline parameter to `enterpriseContractPolicy` 
keeping the stardard camel case format.
Change depends on: https://github.com/redhat-appstudio/release-service/pull/123
=> fix: changes enterpriseContractPolicy to camel-case

Dockerfile
- adds `kubectl` to the release-utils image so we can pin the version for the dependent tasks.
PR: https://github.com/hacbs-release/release-bundles/pull/57
=> chore: add kubectl to release-utils image

catalog/pipeline/fbc-release/0.1/README.md, catalog/pipeline/fbc-release/0.1/fbc-release.yaml, catalog/pipeline/fbc-release/0.1/samples/sample_release_PipelineRun.yaml, catalog/pipeline/fbc-release/0.1/tests/run.yaml, catalog/task/create-internal-request/0.1/README.md, catalog/task/create-internal-request/0.1/create-internal-request.yaml, catalog/task/create-internal-request/0.1/samples/sample_create-internal-request_TaskRun.yaml, catalog/task/create-internal-request/0.1/tests/run.yaml, catalog/task/create-internal-request/OWNERS
Replaces https://github.com/hacbs-release/release-bundles/pull/54
Adds new Pipelines for Release FBC components.
- adds FBC Release Pipeline
- adds create-internal-request task
=> feat(hacbs_1267): adds new FBC PipelineRun bundle

catalog/pipeline/release/0.4/release.yaml
Replacing the url of task push-snapshot to the correct one in default release pipeline
=> fix: replace push-snapshot url task to correct one

.github/scripts/tkn_push_bundles.sh, catalog/pipeline/release/0.5/README.md, catalog/pipeline/release/0.5/release.yaml, catalog/pipeline/release/0.5/samples/sample_release_PipelineRun.yaml, catalog/pipeline/release/0.5/tests/run.yaml
* Fix the task names in the release pipeline to use the ones prepended by task- as those are the only ones our CI updates
* Fix the CI to update the main tag of the bundles on push as well
=> Fix release pipeline

catalog/task/skopeo-inspect/0.1/README.md, catalog/task/skopeo-inspect/0.1/samples/sample_skopeo-inspect_TaskRun.yaml, catalog/task/skopeo-inspect/0.1/skopeo-inspect.yaml, catalog/task/skopeo-inspect/0.1/tests/run.yaml, catalog/task/skopeo-inspect/OWNERS
This commit adds a task to the catalog that executes skopeo-inspect on the passed image and saves the output to a file in the mounted workspace.
=> feat(HACBS-1259): add skopeo-inspect task

catalog/task/create-internal-request/0.1/create-internal-request.yaml
- adds missing quotes on `overwriteFromIndex` param value to preserve its type.
=> fix: missing quotes to preserve string type

.github/workflows/dockerfile_push.yaml
I'll update the tasks in the next PR - I want the image to exist first
=> feat(HACBS-1635): change base image name to release-base-image

catalog/pipeline/fbc-release/0.2/fbc-release.yaml, catalog/task/create-internal-request/0.1/create-internal-request.yaml
The InternalRequest CR already can be created but the tasks and pipeline need changes to be able to watch the InternalRequest state.
- adds `watch-internal-request-status` step
- adds `requestUpdateTimeout` param to fbc-release
- adds `results` to pipeline and tasks
=> feat(hacbs-1325): adds step to check InternalRequest state and updating parameters

catalog/task/create-pyxis-image/0.1/README.md, catalog/task/create-pyxis-image/0.1/create-pyxis-image.yaml, catalog/task/create-pyxis-image/0.1/samples/sample_create-pyxis-image_TaskRun.yaml, catalog/task/create-pyxis-image/0.1/tests/run.yaml, catalog/task/create-pyxis-image/OWNERS
This commit adds a tekton task to the catalog that pushes metadata to pyxis to create a containerImage entry.
=> feat(HACBS-1261): add task to create image in pyxis

.github/scripts/tkn_push_bundles.sh, .github/workflows/tekton_bundle_push.yaml
We have some curl commands to check if a repo exists, and if it does not, to create it. tkn bundle push creates a new repo if it does not exist for free, so I am not sure why the curl commands are in there. This commit removes them.
=> fix: enable automation to create quay repos

catalog/task/prepare-skopeo-image-string/0.1/README.md, catalog/task/prepare-skopeo-image-string/0.1/prepare-skopeo-image-string.yaml, catalog/task/prepare-skopeo-image-string/0.1/samples/sample_prepare-skopeo-image-string_TaskRun.yaml, catalog/task/prepare-skopeo-image-string/0.1/tests/run.yaml, catalog/task/prepare-skopeo-image-string/OWNERS
This commit adds a new task named prepare-skopeo-image-string that is intended to create a string that can be passed to skopeo from a snapshot.
=> feat(HACBS-1262): add prepare-skopeo-image-string task

catalog/task/prepare-skopeo-image-string/0.1/prepare-skopeo-image-string.yaml
=> fix(HACBS-1262): cleanup bash in prepare-skopeo-image-string

catalog/task/create-pyxis-image/0.1/create-pyxis-image.yaml
=> fix: wrong result name in create-pyxis-image

catalog/pipeline/fbc-release/0.4/fbc-release.yaml, catalog/task/create-internal-request/0.1/create-internal-request.yaml
- adds proper default value for `fbc-release` pipeline params
=> fix: adds proper default value from Pipeline params

catalog/pipeline/push-to-external-registry/0.1/push-to-external-registry.yaml, catalog/task/create-pyxis-image/0.1/README.md, catalog/task/create-pyxis-image/0.1/create-pyxis-image.yaml, catalog/task/create-pyxis-image/0.1/samples/sample_create-pyxis-image_TaskRun.yaml, catalog/task/create-pyxis-image/0.1/tests/run.yaml
This commit switches the create-pyxis-image task to use the mapped location in the snapshot (repository) instead of the origin location (containerImage).
=> fix(HACBS-1262): use mapped location in create-pyxis-image task

catalog/pipeline/push-to-external-registry/0.3/README.md, catalog/pipeline/push-to-external-registry/0.3/push-to-external-registry.yaml, catalog/pipeline/push-to-external-registry/0.3/samples/sample_push-to-external-registry_PipelineRun.yaml, catalog/pipeline/push-to-external-registry/0.3/tests/run.yaml, catalog/task/create-pyxis-image/0.3/README.md, catalog/task/create-pyxis-image/0.3/create-pyxis-image.yaml, catalog/task/create-pyxis-image/0.3/samples/sample_create-pyxis-image_TaskRun.yaml, catalog/task/create-pyxis-image/0.3/tests/run.yaml, catalog/task/push-snapshot/0.4/README.md, catalog/task/push-snapshot/0.4/push-snapshot.yaml, catalog/task/push-snapshot/0.4/samples/sample_push-snapshot_TaskRun.yaml, catalog/task/push-snapshot/0.4/tests/run.yaml
support the ability to use the Release Strategy existing tag parameter in the push-snapshot task instead of hard-coded latest
```
- name: push-snapshot
taskRef:
name: push-snapshot
bundle: quay.io/hacbs-release/task-push-snapshot:main
params:
- name: mappedSnapshot
value: $(tasks.apply-mapping.results.snapshot)
- name: tag
value: $(params.tag) 
```
```
- name: tag
description: tag name to create on external registry
type: string
default: "latest"
```
` data[tag]="${data[tag]:=$(params.tag)}"`
=> fix(hacbs-1829): use tag param

catalog/task/push-snapshot/0.5/README.md, catalog/task/push-snapshot/0.5/push-snapshot.yaml
The push-snapshot task is hanging on repos with a lot of tags. This commit adds the --no-tags flag to the skopeo inspects that are run as part of the push-snapshot task to prevent timeout issues.
=> fix(STONEBUGS-24): inspect without tags in push-snapshot

catalog/pipeline/push-to-external-registry/0.5/README.md, catalog/pipeline/push-to-external-registry/0.5/push-to-external-registry.yaml, catalog/pipeline/push-to-external-registry/0.5/samples/sample_push-to-external-registry_PipelineRun.yaml, catalog/pipeline/push-to-external-registry/0.5/tests/run.yaml, catalog/task/push-snapshot/0.6/README.md, catalog/task/push-snapshot/0.6/push-snapshot.yaml, catalog/task/push-snapshot/0.6/samples/sample_push-snapshot_TaskRun.yaml, catalog/task/push-snapshot/0.6/tests/run.yaml
This PR adds the `addGitShaTag` parameter to the `push-snapshot` task. When true, a sha will be looked for in the snapshot for each component and a tag will be pushed with said sha when pushing to the external registry
The work to inject the git sha in the snapshot is not yet complete, so marking this as do not merge for now
=> feat(HACBS-2011): task push-snapshot can push a tag with git sha

catalog/pipeline/release/0.9/README.md, catalog/pipeline/release/0.9/release.yaml
The pipeline named release uses push-snapshot:main. The push-snapshot task was modified to add git sha tags, with task default to true. However, this functionality is not ready yet, so pipelines calling this task should pass this parameter as false for now.
=> fix(HACBS-2061): pipeline-release should use addGitShaTag false

.github/scripts/tkn_push_bundles.sh
If a commit changes a bundle version, it is pushed to main by the GitHub actions. This should not be the case all the time, only if the bundle version is the latest one we have. This commit fixes that.
=> fix(HACBS-2063): only push latest version to main tag

catalog/pipeline/fbc-release/0.9/README.md, catalog/pipeline/fbc-release/0.9/fbc-release.yaml, catalog/pipeline/fbc-release/0.9/samples/sample_release_PipelineRun.yaml, catalog/pipeline/fbc-release/0.9/tests/run.yaml, catalog/task/publish-index-image/0.1/README.md, catalog/task/publish-index-image/0.1/publish-index-image.yaml, catalog/task/publish-index-image/0.1/samples/publish-index-image_TaskRun.yaml, catalog/task/publish-index-image/0.1/tests/run.yaml, catalog/task/publish-index-image/OWNERS
FBC Pipeline should copy the signed index image produced by IIB to the final public location
=> feat(HACBS-1823): copy index image produced by IIB to final signed public location

.github/workflows/tekton_bundle_push.yaml
tkn  v0.18 can't parse the fbc-release.yaml after `create-internal-request` change, but newer can.
- upgrades to `v0.26.0`
=> chore: upgrade tkn version on action

.github/workflows/tekton_bundle_push.yaml
The action that was used hasn't been updated
in years and it's just two commands, so it makes
sense to install tkn directly rather than rely
on a community action.
Also, update the checkout action to v3. v2 is deprecated.
Note that I tested both the updated checkout action and the new install tkn step in a custom workflow here: https://github.com/mmalina/release-service-bundles/actions/runs/4785630080
=> fix(HACBS-2139): install tkn directly in gh workflow

catalog/pipeline/push-to-external-registry/0.7/README.md, catalog/pipeline/push-to-external-registry/0.7/push-to-external-registry.yaml, catalog/pipeline/push-to-external-registry/0.7/samples/sample_push-to-external-registry_PipelineRun.yaml, catalog/pipeline/push-to-external-registry/0.7/tests/run.yaml, catalog/task/push-sbom-to-pyxis/0.1/README.md, catalog/task/push-sbom-to-pyxis/0.1/push-sbom-to-pyxis.yaml, catalog/task/push-sbom-to-pyxis/0.1/sample/sample_push-sbom-to-pyxis_TaskRun.yaml, catalog/task/push-sbom-to-pyxis/0.1/tests/run.yaml
This will ensure that sbom components for the image are pushed to Pyxis as part of this pipeline.
Also, modify push-sbom-to-pyxis task to use mappedSnapshot instead of image urls as a parameter - we don't have the urls ready in the pipeline, so we'll have to get them from the snapshot.
Note that while this PR is adding a new version of push-to-external-registry, the push-sbom-to-pyxis task remains at version 0.1 since it's not used anywhere yet, so there shouldn't be any need for a new version.
=> feat(HACBS-1554): add push-sbom-to-pyxis task to push-to-external-registry

catalog/task/push-sbom-to-pyxis/0.1/push-sbom-to-pyxis.yaml
Repository does not refer to a specific image in the registry, for that we need to use the containerImage parameter of the snapshot.
Here's an example of a component:
{"name":"dc-metro-map","containerImage":"quay.io/redhat-appstudio-qe/dcmetromap@sha256:8de2af658331295ae0401478a179b9b0e0b8fcacd5f6b20d507b12100e2648f7","repository":"quay.io/hacbs-release-tests/dcmetromap"}
FYI, this came up here: https://issues.redhat.com/browse/RHTAPBUGS-197
The underlying issue of the bug is different, but in the log I noticed that the `cosign download sbom` command is missing the image sha.
=> fix: use containerImage instead of repository to fetch sbom

catalog/task/push-sbom-to-pyxis/0.1/push-sbom-to-pyxis.yaml
It was missing the trailing /graphql/ - this was also missing in pyxis documentation but it turns out it was an oversight.
I tested the full script execution with the staging instance - it successfully created a manifest and all the components. For prod, I only verified that running the `get_image` query for a non-existing image returns `"Not found"` - that confirms that the api is working and that the user crt+key is also working (with a different one I get `"You don't have a sufficient role for the endpoint.`").
=> fix(RHTAPBUGS-197): pyxis graphql api url was incorrect

catalog/pipeline/release/0.11/README.md, catalog/pipeline/release/0.11/release.yaml, catalog/pipeline/release/0.11/samples/sample_release_PipelineRun.yaml, catalog/pipeline/release/0.11/tests/run.yaml
Bump the tag used in the ec task bundle the the latest.
The specific motivation for doing this now is this test failure:
invalid uri: uri missing scheme prefix
The failure is related to this unmerged chains upstream PR: https://github.com/tektoncd/chains/pull/792 which has an ec workaround in https://github.com/enterprise-contract/ec-cli/pull/649 .
IIUC updating the task bundle should mean the version of ec used includes this workaround should get the tests passing.
There are other changes to the task definition which might cause breakages in other ways, so we'll need to monitor the next test run and see how it goes.
Note that there are over two months of changes since the last update. To see everything that changed we can look at the diff in the ec-cli repo, e.g. `git diff 7f2e25e …
=> fix(RHTAPBUGS-254): Add version 0.11 ec task update

.github/actions/install-tkn/action.yaml, .github/scripts/tkn_check_parse.sh, .github/workflows/lint.yaml, .github/workflows/tekton_bundle_push.yaml
To avoid breaking the github action that publish the bundles, we need to
check that the new versions are properly parsed by the `tkn` version
used by the github action.
- adds script `tkn_check_parse.sh`
- updates the lint workflow adding the tkn check
=> feat(HACBS-2140): add tkn check for PRs in release-service-bundles repo

catalog/pipeline/push-to-external-registry/0.10/README.md, catalog/pipeline/push-to-external-registry/0.10/push-to-external-registry.yaml, catalog/pipeline/push-to-external-registry/0.10/samples/sample_push-to-external-registry_PipelineRun.yaml, catalog/pipeline/push-to-external-registry/0.10/tests/run.yaml, catalog/pipeline/release/0.13/README.md, catalog/pipeline/release/0.13/release.yaml, catalog/pipeline/release/0.13/samples/sample_release_PipelineRun.yaml, catalog/pipeline/release/0.13/tests/run.yaml
This commit changes the default value of the addGitShaTag in the pipelines that use the push-snapshot task from false to true.
=> chore(HACBS-2055): set addGitShaTag to true in pipelines

Dockerfile
add `opm` tool to the release base image
=> chore(noticket): adds opm to base image

.github/workflows/tekton_task_tests.yaml
The workflow is supposed to pick up versioned task dirs
(the directories that contain the task definitions)
that were changed and to run tests for each of them.
Before this fix, it could also pick up a directory one
level up. E.g. if catalog/task/kubernetes-actions/OWNERS
was changed, it would include catalog/task/kubernetes-actions
in the list of changed directories.
For reference, this issue was spotted in Johnny's PR here: https://github.com/redhat-appstudio/release-service-bundles/pull/124
Signed-off-by: Martin Malina <mmalina@redhat.com>
=> fix: wrong files pattern for task tests workflow

catalog/task/collect-extra-data/0.1/README.md, catalog/task/collect-extra-data/0.1/collect-extra-data.yaml, catalog/task/collect-extra-data/0.1/samples/sample_collect-extra-data_TaskRun.yaml, catalog/task/collect-extra-data/0.1/tests/run.yaml, catalog/task/collect-extra-data/OWNERS
This commit adds a new task to collect the information in the extraData field from the Release, the ReleasePlan and the ReleasePlanAdmission resources. The data in those fields is merged, with keys being overwritten taking into account the following priority chain: RPA > RP > R.
=> feat(HACBS-2225): add task to collect extra data

catalog/pipeline/fbc-release/0.12/README.md, catalog/pipeline/fbc-release/0.12/fbc-release.yaml, catalog/pipeline/fbc-release/0.12/samples/sample_release_PipelineRun.yaml, catalog/pipeline/fbc-release/0.12/tests/run.yaml, catalog/task/create-internal-request/0.6/README.md, catalog/task/create-internal-request/0.6/create-internal-request.yaml, catalog/task/create-internal-request/0.6/samples/sample_create-internal-request_TaskRun.yaml, catalog/task/create-internal-request/0.6/tests/run.yaml
feat(HACBS-2207): fbc-release must overwrite fromIndex for opt-in images
- updates fbc-release to 0.12
- removes overwriteFromIndex parameter
- updates pipeline to use create-internal-request version 0.6
- changes publish-index-image to use create-internal-request so the
publishing can be done throught the internal cluster
- only publishes FBC indexes when the fragment is opt-in
- updates task create-internal-request to 0.6
- updates `release-base-image` to the latest version
=> feat(HACBS-2207): Production IIB pipeline only overwrites fromImage and copies to targetImage when opted-in

.github/workflows/tekton_bundle_push.yaml, .github/workflows/tekton_task_tests.yaml, catalog/task/upstream/tekton/kubernetes-actions/0.2/README.md, catalog/task/upstream/tekton/kubernetes-actions/0.2/kubernetes-actions.yaml, catalog/task/upstream/tekton/kubernetes-actions/0.2/tests/run.yaml, catalog/task/upstream/tekton/kubernetes-actions/OWNERS
This adds a copy of the upstream task `kubernetes-actions` to the repository. This task allows to run whatever `kubectl` command is passed as the script parameter, and the output is saved as `output-result`.
=> feat(HACBS-2130): add kubernetes-actions upstream task

catalog/pipeline/fbc-release/0.14/README.md, catalog/pipeline/fbc-release/0.14/fbc-release.yaml, catalog/pipeline/fbc-release/0.14/samples/sample_release_PipelineRun.yaml, catalog/pipeline/fbc-release/0.14/tests/run.yaml
The version `0.12` removes the param `fbcPublishingCredentials` but it is actually required
as we might need to set different publishing secrets per environment in the same namespace 
(ie. stage and pre-GA) in stage *cluster*.
=> fix: adds fbcPublishingCredentials param back to the pipeline

catalog/pipeline/fbc-release/0.15/README.md, catalog/pipeline/fbc-release/0.15/fbc-release.yaml, catalog/pipeline/fbc-release/0.15/samples/sample_release_PipelineRun.yaml, catalog/pipeline/fbc-release/0.15/tests/run.yaml
Pre-GA and prod FBC components might be built in the same namespace so they need to have different secrets specified in the releaseStrategy
=> chore(noticket): adds parameters required to enable pre-GA builds

catalog/task/push-sbom-to-pyxis/0.1/push-sbom-to-pyxis.yaml
The upload_sbom script was refactored to account for changes in Pyxis api (some embedded objects are being removed):
https://github.com/redhat-appstudio/release-service-utils/pull/41
The functionality is identical, so a new version should not be needed.
=> refactor(HACBS-2375): update utils image in push-sbom-to-pyxis task

catalog/pipeline/deploy-release/0.4/deploy-release.yaml, catalog/pipeline/fbc-release/0.16/fbc-release.yaml, catalog/pipeline/push-to-external-registry/0.12/push-to-external-registry.yaml, catalog/pipeline/release/0.15/release.yaml
In order for the verify-enterprise-contract task to be backwards compatible, they need us to pass the absolute path to the snapshot, not just the filename.
=> refactor(HACBS-2290): pass absolute path to ec task

catalog/task/push-sbom-to-pyxis/0.2/push-sbom-to-pyxis.yaml
I didn't realize there were two image lines in [!140](https://github.com/redhat-appstudio/release-service-bundles/pull/141)
=> chore: update utils image in push sbom task

catalog/task/push-sbom-to-pyxis/0.2/push-sbom-to-pyxis.yaml
The updated image contains improvements from
https://github.com/redhat-appstudio/release-service-utils/pull/46
=> chore(HACBS-2271): update images in push-sbom-to-pyxis task

.github/workflows/tekton_task_tests.yaml
If the only change to the catalog/task directory is removing stuff, the tekton task tests do not need to run.
=> fix: tekton task test triggering

.github/scripts/test_tekton_tasks.sh
This commit sets up a framework to allow each test directory to have its own pre-apply-task-hook.sh file, following upstream standards. If the file exists, it will be executed before the test files.
=> feat(HACBS-2431): enable task test pre hooks

.github/workflows/tekton_task_tests.yaml, catalog/task/collect-data/0.1/tests/pre-apply-task-hook.sh
This commit moves the pre reqs for the collect-data tests from running for any task test to only running for the collect-data task tests.
=> refactor: only run collect-data prereqs for that task

catalog/task/push-sbom-to-pyxis/0.2/push-sbom-to-pyxis.yaml
This was somehow missed when we added the retry option to the script as part of HACBS-2271 .
The PR that was updating the push-sbom-to-pyxis task only updated the release-util image version
but forgot to actually enable the retry:
https://github.com/redhat-appstudio/release-service-bundles/pull/143
For reference, here's the PR that added the `--retry` option: https://github.com/redhat-appstudio/release-service-utils/pull/46
=> fix(RHTAPBUGS-560): enable retry for upload_sbom script

catalog/task/get-ocp-version/0.1/README.md, catalog/task/get-ocp-version/0.1/get-ocp-version.yaml, catalog/task/get-ocp-version/0.1/samples/sample_get-ocp-version_TaskRun.yaml, catalog/task/get-ocp-version/0.1/tests/test-get-ocp-version.yaml, catalog/task/get-ocp-version/OWNERS
This PR will add a new task to store the OCP version from the fbcFragment (image) and store it as a task result. 
In HACBS-2293 this stored result will validate the correct version being used in the strategy for fromIndex and targetIndex.
=> feat(HACBS-2292): get ocp version from an image

catalog/pipeline/rhtap-service-push/0.1/rhtap-service-push.yaml
- add slack-webhook-notification to rhtap-service-push pipeline in finally section.
=> feat(HACBS-2471): Add slack support to rhtap service push

catalog/task/collect-data/0.1/collect-data.yaml, catalog/task/collect-data/0.1/tests/test-collect-data.yaml
The fbc-release's task `add-fbc-add-fbc-contribution-to-index-image`
is failing due to an extra "\n" added by `collectd-data` to the
fbcFragment result, which is now used by the task.
=> fix(HACBS-2533): fbc-release pipelinerun failing

.github/scripts/test_tekton_tasks.sh
This script runs as part of PR checks on Github
and sometimes it gets stuck on this command:
`tkn pr logs $PIPELINERUN -f`
"-f" stands for follow. It seems sometimes it has issues following the logs - it does and then gets stuck.
This should avoid the issue, but at the price
of not being able to see the log live as
the PR runs. It will be spit out once the PR finishes.
This came up during review of https://github.com/redhat-appstudio/release-service-bundles/pull/169
=> fix: improve reliability of test_tekton_task script

catalog/task/apply-mapping/0.6/README.md, catalog/task/apply-mapping/0.6/apply-mapping.yaml, catalog/task/apply-mapping/0.6/samples/sample_apply-mapping_TaskRun.yaml, catalog/task/apply-mapping/0.6/tests/test-apply-mapping-fail-on-empty.yaml, catalog/task/apply-mapping/0.6/tests/test-apply-mapping-no-mapping.yaml, catalog/task/apply-mapping/0.6/tests/test-apply-mapping.yaml, catalog/task/collect-data/0.2/README.md, catalog/task/collect-data/0.2/collect-data.yaml, catalog/task/collect-data/0.2/samples/sample_collect-extra-data_TaskRun.yaml, catalog/task/collect-data/0.2/tests/pre-apply-task-hook.sh, catalog/task/collect-data/0.2/tests/test-collect-data-fail-missing-cr.yaml, catalog/task/collect-data/0.2/tests/test-collect-data-with-extra-data.yaml, catalog/task/collect-data/0.2/tests/test-collect-data.yaml
This is to avoid multiple PRs running in parallel overriding each other's data.
This updates the tasks to be able to use a subdirectory inside a workspace.
There will be another PR to update the pipelines to use these.
=> fix(RHTAPBUGS-560): add subdirectory parameter to tasks

catalog/pipeline/deploy-release/0.6/README.md, catalog/pipeline/deploy-release/0.6/deploy-release.yaml, catalog/pipeline/deploy-release/0.6/samples/sample_release_PipelineRun.yaml, catalog/pipeline/deploy-release/0.6/tests/run.yaml, catalog/pipeline/fbc-release/0.18/README.md, catalog/pipeline/fbc-release/0.18/fbc-release.yaml, catalog/pipeline/fbc-release/0.18/samples/sample_release_PipelineRun.yaml, catalog/pipeline/fbc-release/0.18/tests/run.yaml, catalog/pipeline/push-to-external-registry/0.16/README.md, catalog/pipeline/push-to-external-registry/0.16/push-to-external-registry.yaml, catalog/pipeline/push-to-external-registry/0.16/samples/sample_push-to-external-registry_PipelineRun.yaml, catalog/pipeline/push-to-external-registry/0.16/tests/run.yaml, catalog/pipeline/release/0.18/README.md, catalog/pipeline/release/0.18/release.yaml, catalog/pipeline/release/0.18/samples/sample_release_PipelineRun.yaml, catalog/pipeline/release/0.18/tests/run.yaml, catalog/pipeline/rhtap-service-push/0.2/README.md, catalog/pipeline/rhtap-service-push/0.2/rhtap-service-push.yaml, catalog/pipeline/rhtap-service-push/0.2/samples/sample_push-to-external-registry_PipelineRun.yaml, catalog/pipeline/rhtap-service-push/0.2/tests/run.yaml, catalog/task/create-internal-request/0.7/README.md, catalog/task/create-internal-request/0.7/create-internal-request.yaml, catalog/task/create-internal-request/0.7/samples/sample_create-internal-request_TaskRun.yaml, catalog/task/create-internal-request/0.7/tests/run.yaml
These changes will fix the issue of pipeline runs running in parallel overriding each other's data.
- create new pipeline versions
- use new version of collect-data with subdirectory
- use new version of apply-mapping that overrides original snapshot_spec file
- create new version of create-internal-requests that also uses a subdirectory and use it in the fbc-release pipeline
- make sure all pipelines clean up the subdirectory in the workspace at the end
=> fix(RHTAPBUGS-560): update pipelines to use subdirectory

catalog/task/create-internal-request/0.7/create-internal-request.yaml
fix: missing ")" char after evaluated command
This PR fixes the missing ")" char after the evaluated command
to get the REASON in the status.
=> fix: missing ")" after command block
